name: Build and Deploy Docker Images

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: self-hosted  # Assuming you're using a self-hosted runner on EC2
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        case "${{ github.event.inputs.app }}" in
          python)
          ./my_python_app
            ;;
          java)
         ./my_java_app
            ;;
          nodejs)
          ./my_node_app
            ;;
          *)
            echo "Invalid application selected"
            exit 1
            ;;
        esac
    # Python App Build and Run
    - name: Build Python Docker image
      run: |
        cd ./my_python_app
        docker build -t python-app-image .

    - name: Run Python Docker container
      run: |
        docker run -d -p 5000:5000 --name python-app-container python-app-image

    # Java App Build and Run
    - name: Build Java Docker image
      run: |
        cd ../my_java_app
        docker build -t java-app-image .

    - name: Run Java Docker container
      run: |
        docker run -d -p 8080:8080 --name java-app-container java-app-image

    # Node.js App Build and Run
    - name: Build Node.js Docker image
      run: |
        cd ../my_nodejs_app
        docker build -t nodejs-app-image .

    - name: Run Node.js Docker container
      run: |
        docker run -d -p 3000:3000 --name nodejs-app-container nodejs-app-image

    # List all running containers
    - name: List running containers
      run: docker ps
