name: Buil the selected application

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image for python
        if: ${{ github.event.inputs.app == 'python' }}
        run: |
          cd my_python_app
          docker build -t my-python-image .

      - name: Build docker image for java
        if: ${{ github.event.inputs.app == 'Java' }}
        run: |
          cd my_java_app
          docker build -t my-java-image .

      - name: Build docker image for node
        if: ${{ github.event.inputs.app == 'nodejs' }}
        run: |
          cd my_node_app
          docker build -t my-nodejs-image .

      - name: Show Docker image
        run: docker images
