name: build apps in one job using if and env

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_DIR: python
      PY_IMAGE: python-image
      JAVA_DIR: java
      JAVA_IMAGE: java-image
      NODE_DIR: node
      NODE_IMAGE: node-image
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image for python
        if: ${{ github.event.inputs.app == 'python' }}
        run: |
          cd my_${{ env.PY_DIR }}_app
          docker build -t ${{ env.PY_IMAGE }} .

      - name: Build docker image for java
        if: ${{ github.event.inputs.app == 'Java' }}
        run: |
          cd my_${{ env.JAVA_DIR }}_app
          docker build -t ${{ env.JAVA_IMAGE }} .

      - name: Build docker image for node
        if: ${{ github.event.inputs.app == 'nodejs' }}
        run: |
          cd my_${{ env.NODE_DIR }}_app
          docker build -t ${{ env.NODE_IMAGE }} .

      - name: Show Docker image
        run: docker images
