name: Build Docker Image

# This workflow will be triggered manually
on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        default: 'nodejs'
        type: choice
        options:
          - python
          - java
          - nodejs

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        case "${{ github.event.inputs.app }}" in
          python)
            docker build -t python-app:latest ./my_python_app
            ;;
          java)
            docker build -t java-app:latest ./my_java_app
            ;;
          nodejs)
            docker build -t nodejs-app:latest ./my_node_app
            ;;
          *)
            echo "Invalid application selected"
            exit 1
            ;;
        esac

    - name: Verify Docker image
      run: |
        docker images ${{ github.event.inputs.app }}-app:latest

