# name: Build Selected Application

# on:
#   workflow_dispatch:
#     inputs:
#       app:
#         description: 'Select the application to build'
#         required: true
#         type: choice
#         options:
#           - python
#           - Java
#           - nodejs

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v3

#       - name: Setup Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Set environment variables
#         run: |
#           echo "APP_DIR=${{ github.event.inputs.app }}" >> $GITHUB_ENV
#           echo "DOCKER_IMAGE=my-${{ github.event.inputs.app }}-image" >> $GITHUB_ENV

#       - name: Build the Docker image
#         run: |
#           # Map directory names based on input
#           declare -A directories
#           directories[python]="my_python_app"
#           directories[Java]="my_java_app"
#           directories[nodejs]="my_nodejs_app"

#           # Get the directory and image name from environment variables
#           dir=${directories[$APP_DIR]}
#           image=$DOCKER_IMAGE

#           # Check if the directory is valid and build the Docker image
#           if [ -d "$dir" ]; then
#             echo "Building Docker image for $APP_DIR..."
#             cd $dir
#             docker build -t $image .
#             cd ..
#           else
#             echo "Directory $dir does not exist."
#             exit 1
#           fi

#       - name: Check the Docker images
#         run: docker images
