name: Build Python, Node.js, and Java Applications Separately

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [python, Java, nodejs]  

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        run: |
          directories=("my_python_app" "my_java_app" "my_node_app")
          images=("my-python-image" "my-java-image" "my-nodejs-image")

          index=0
          if [ "${{ matrix.app }}" == "Java" ]; then
            index=1
          elif [ "${{ matrix.app }}" == "nodejs" ]; then
            index=2
          fi

          echo "Building Docker image for ${{ matrix.app }}..."
          cd ${directories[$index]}
          docker build -t ${images[$index]} .
          cd ..

      - name: Check the Docker images
        run: docker images
