name: one build file

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - node

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_DIR: "my_${{ github.event.inputs.app }}_app"
      APP_IMAGE: "my-${{ github.event.inputs.app }}-image"

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          dir="${{ env.APP_DIR }}"
          image="${{ env.APP_IMAGE }}"
          echo "Build the Docker image for ${dir} and name is ${image}"
          cd $dir
          docker build -t $image .

      - name: Show Docker images
        run: docker images
