name: Buil the selected application

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - nodejs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_DIR: python
      PY_IMAGE: python
      JAVA_DIR: java
      JAVA_IMAGE: java
      NODE_DIR: node
      NODE_IMAGE: node
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image for python, java and nodejs
        run: |
          cd my_${{ env.PY_DIR }}_app
          docker build -t my-${{ env.PY_IMAGE }}-image .
          cd my_${{ env.JAVA_DIR }}_app
          docker build -t my-${{ env.JAVA_IMAGE }}-image .
          cd my_${{ env.NODE_DIR }}_app
          docker build -t my-${{ env.NODE_IMAGE }}-image .


      - name: Show Docker image
        run: docker images
