name: one step build file

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          app="${{ github.event.inputs.app }}"
          dir="my_${app}_app"
          image="my-${app}-image"
        
          echo "Build image $dir with image $image"
          
          cd $dir
          docker build -t $image .

      - name: Show Docker images
        run: docker images
