name: build apps in one job and one step

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: choice
        options:
          - python
          - Java
          - node

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PY_DIR: python
      PY_IMAGE: python-image
      JAVA_DIR: java
      JAVA_IMAGE: java-image
      NODE_DIR: node
      NODE_IMAGE: node-image

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd my_${{ env.PY_DIR }}_app
          docker build -t ${{ env.PY_IMAGE }} .

      - name: Show Docker images
        run: docker images
