name: secrets test

on:
  workflow_dispatch:


jobs:
  secrets_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo ${{ secrets.MY_VALUE }}
