name: set the job output 

on:
  workflow_dispatch:



jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
        job1_name: ${{ steps.set-output.outputs.name }}

    steps:
      - name: set output
        id: set-output
        run: |
            echo "name=aqeel" >> $GITHUB_OUTPUT
      - name: access output
        run: echo "${{ steps.set-output.outputs.name }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Access output
        run: echo "my name is ${{ needs.job1.outputs.job1_name }}"
