name: set the output

on:
  workflow_dispatch:



jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: set output
        id: set-output
        run: |
            echo "age=24" >> $GITHUB_OUTPUT
            echo "name=Aqeel" >> $GITHUB_OUTPUT


      - name: Access output
        run: |
            echo "My age is ${{ steps.set-output.outputs.age }}"
            echo "My name is ${{ steps.set-output.outputs.name }}"

