name: store and access secrets

on:
  push:
    branches:
       - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Store and access secrets
          run: echo "i want to access secrets ${{ secrets.MY_NAME }}"