name: workflow file 

on:
  workflow_call:
    # inputs:
    #   app_name:
    #     description: 'The app name to build the Docker image for'
    #     required: true
    #     type: string
    secrets:
      APP_DIR:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2


      - name: show dir and img
        run: |
          echo "${{ vars.APP_IMAGE }}"        
          echo "${{ secrets.APP_DIR }}"

     
      - name: Build Docker image
        run: |
          cd my_${{ secrets.APP_DIR }}_app
          docker build -t my-${{ vars.APP_IMAGE }}-app .

      - name: Show Docker images
        run: docker images
