name: workflow file

on:
  workflow_call:
    inputs:
      app:
        description: 'Select the application to build'
        required: true
        type: string
        default: python

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd my_${{ github.event.inputs.app }}_app
          docker build -t my-${{ github.event.inputs.app}}-image .

      - name: Show Docker images
        run: docker images
