name: workflow file 

on:
  workflow_call:
    secrets:
      MY_APP:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd my_${{ secrets.MY_APP }}_app
          docker build -t my-${{ secrets.MY_APP }}-image .

      - name: Show Docker images
        run: docker images
