name: workflow file 

on:
  workflow_call:
    inputs:
      app_name:
        description: 'The app name to build the Docker image for'
        required: true
        type: string
    secrets:
      MY_APP_DIRS:
        required: true
      MY_APP_IMAGES:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          cd echo '${{ secrets.MY_APP_DIRS }}' >> $GITHUB_ENV
          docker build -t echo '${{ secrets.MY_APP_IMAGES }}' >> $GITHUB_ENV .

      - name: Show Docker images
        run: docker images
